export const GRID_LAYOUT = {
  rows: [0, 1, 2, 3, 4],
  cols: [0, 1, 2, 3, 4, 5, 6, 7],
  media: [
    {
      row: 0,
      col: 0,
      type: "image",
      src: "/images/rove/app/app_mockup.png",
      alt: "Rove App",
      brightness: 2.4,
      blur: 6,
      scale: 1.15,
      hoverText: "Rove",
    },
    {
      row: 0,
      col: 1,
      type: "image",
      src: "/images/rove/card/card_render_1.png",
      alt: "Rove Card",
      brightness: 2,
      blur: 4,
      scale: 1.4,
      hoverText: "Rove",
    },
    {
      row: 0,
      col: 4,
      type: "image",
      src: "/images/paradigm/logo/paradigm_logo_dark.png",
      alt: "Image 1",
      brightness: 3.7,
      blur: 8,
      scale: 1.24,
      hoverText: "Paradigm",
    },
    {
      row: 0,
      col: 5,
      type: "image",
      src: "/images/paradigm/logo/paradigm_shirt.png",
      alt: "Paradigm Shirt",
      brightness: 2,
      blur: 6,
      scale: 1.24,
      hoverText: "Paradigm",
    },
    {
      row: 1,
      col: 0,
      type: "video",
      src: "/images/dg/dg_animation.mp4",
      alt: "Dolce&Gabbana Website",
      brightness: 2.4,
      blur: 4,
      scale: 1.21,
      hoverText: "Dolce & Gabbana",
    },
    {
      row: 1,
      col: 2,
      type: "image",
      src: "/images/ayamuse/am_1.png",
      alt: "Aya Muse Website",
      brightness: 3.2,
      blur: 6,
      scale: 1.24,
      hoverText: "Aya Muse",
    },
    {
      row: 1,
      col: 7,
      type: "image",
      src: "/images/cognition/cognition.png",
      alt: "Cognition Website",
      brightness: 1,
      blur: 2,
      scale: 1.18,
      hoverText: "Cognition",
    },
    {
      row: 2,
      col: 4,
      type: "image",
      src: "/images/cognition/cognition_white.png",
      alt: "Cognition Graphic",
      brightness: 2,
      blur: 2,
      scale: 1.24,
      hoverText: "Cognition",
    },
    {
      row: 2,
      col: 6,
      type: "image",
      src: "/images/explorations/mobius_2.png",
      alt: "3D Mobius",
      brightness: 5,
      blur: 4,
      scale: 1.38,
      hoverText: "Explorations",
    },
    {
      row: 3,
      col: 0,
      type: "image",
      src: "/images/explorations/ai_value.png",
      alt: "Image 2",
      brightness: 1.05,
      blur: 2,
      scale: 1.16,
      hoverText: "Explorations",
    },
    {
      row: 3,
      col: 2,
      type: "image",
      src: "/images/paradigm/product/paradigm_product_1.png",
      alt: "Paradigm Product",
      brightness: 1.1,
      blur: 5,
      scale: 1.26,
      hoverText: "Paradigm",
    },
    {
      row: 3,
      col: 7,
      type: "image",
      src: "/images/blackster/blackster_re.png",
      alt: "",
      brightness: 2.5,
      blur: 5,
      scale: 1.19,
      hoverText: "Blackster",
    },
    {
      row: 4,
      col: 5,
      type: "image",
      src: "/images/blackster/blackster_com.png",
      alt: "Blackster Website",
      brightness: 1.4,
      blur: 4,
      scale: 1.14,
      hoverText: "Blackster",
    },
  ],
};
