import styles from "@/components/Home/Hero/Hero.module.css";

export const GRID_LAYOUT = {
  rows: [0, 1, 2, 3, 4],
  cols: [0, 1, 2, 3, 4, 5, 6, 7],
  media: [
    {
      row: 0,
      col: 0,
      type: "image",
      src: "/images/rove/app/app_mockup.png",
      alt: "Rove App",
      brightness: 2.4,
      blur: 6,
      scale: 1.14,
      hoverText: "Rove",
      industry: "Airline Mile",
    },
    {
      row: 0,
      col: 1,
      type: "image",
      src: "/images/rove/card/card_render_1.png",
      alt: "Rove Card",
      brightness: 2,
      blur: 4,
      scale: 1.3,
      hoverText: "Rove",
      industry: "Airline Mile",
    },
    {
      row: 0,
      col: 4,
      type: "video",
      src: "/images/paradigm/paradigm_cube.mp4",
      alt: "Paradigm Cube Video",
      brightness: 4,
      blur: 8,
      scale: 1.24,
      hoverText: "Paradigm",
      industry: "AI",
    },
    {
      row: 0,
      col: 5,
      type: "video",
      src: "/images/paradigm/paradigm_launch.mp4",
      alt: "Paradigm Launch Video",
      brightness: 3,
      blur: 4,
      scale: 1.24,
      hoverText: "Paradigm",
      className: `${styles["wide"]}`,
      industry: "AI",
    },
    {
      row: 1,
      col: 0,
      type: "video",
      src: "/images/dg/dg_animation.mp4",
      alt: "Dolce&Gabbana Website",
      brightness: 2.65,
      blur: 5,
      scale: 1.21,
      hoverText: "Dolce & Gabbana",
      industry: "NFT",
    },
    {
      row: 1,
      col: 2,
      type: "image",
      src: "/images/ayamuse/am_1.png",
      alt: "Aya Muse Website",
      brightness: 3.2,
      blur: 6,
      scale: 1.24,
      hoverText: "Aya Muse",
      industry: "Fashion",
    },
    {
      row: 1,
      col: 7,
      type: "video",
      src: "/images/endex/endex_dark.mp4",
      alt: "Endex Website",
      brightness: 1.05,
      blur: 1,
      scale: 1.15,
      hoverText: "Endex",
      styles: {
        backgroundColor: "transparent",
      },
      industry: "AI",
    },
    {
      row: 2,
      col: 4,
      type: "image",
      src: "/images/cognition/cognition.png",
      alt: "Cognition Website",
      brightness: 1.05,
      blur: 1.5,
      scale: 1.2,
      hoverText: "Cognition",
      className: `${styles["cognition"]}`,
      industry: "AI",
    },
    {
      row: 2,
      col: 6,
      type: "image",
      src: "/images/explorations/mobius_2.png",
      alt: "3D Mobius",
      brightness: 5,
      blur: 4,
      scale: 1.38,
      hoverText: "Explorations",
      industry: "3D Art",
    },
    {
      row: 3,
      col: 0,
      type: "image",
      src: "/images/blackster/blackster_logos.png",
      alt: "Blackster Logo",
      brightness: 5.5,
      blur: 2,
      scale: 1.5,
      hoverText: "Blackster",
      className: `${styles["blackster"]}`,
      industry: "Private Equity",
    },
    {
      row: 3,
      col: 2,
      type: "image",
      src: "/images/paradigm/product/paradigm_product_1.png",
      alt: "Paradigm Product",
      brightness: 1.1,
      blur: 5,
      scale: 1.16,
      hoverText: "Paradigm",
      industry: "AI",
    },
    {
      row: 3,
      col: 7,
      type: "video",
      src: "/images/align/align_1.mp4",
      alt: "Align Website",
      brightness: 4,
      blur: 2,
      scale: 1.84,
      hoverText: "Align",
      className: `${styles["align"]}`,
      industry: "Private Equity",
    },
    {
      row: 4,
      col: 5,
      type: "video",
      src: "/images/explorations/crystal.mp4",
      alt: "Crystal 3D Art",
      brightness: 2.5,
      blur: 6,
      scale: 1.2,
      hoverText: "Explorations",
      industry: "3D Art",
    },
  ],
};
