import styles from "@/components/Home/Hero/Hero.module.css";
import { supportsHEVCAlpha } from "@/hooks/utils/useSupportsHEVC";

const isHEVC = supportsHEVCAlpha();

const getResponsivePaths = (filename, type) => {
  let format;
  if (type !== "image") {
    format = isHEVC ? "mp4" : "webm";
  } else {
    format = "avif";
  }
  const basePath = "/images/optimized";
  return {
    mobile: `${basePath}/300/${format}/${filename}.${format}`,
    desktop: `${basePath}/400/${format}/${filename}.${format}`,
    largeDesktop: `${basePath}/650/${format}/${filename}.${format}`,
  };
};

export const GRID_LAYOUT_DESKTOP = {
  rows: [0, 1, 2, 3, 4],
  cols: [0, 1, 2, 3, 4, 5, 6, 7],
  media: [
    {
      row: 0,
      col: 0,
      type: "image",
      src: getResponsivePaths("app_mockup", "image"),
      alt: "Rove App",
      brightness: 2,
      blur: 6,
      scale: 1.14,
      hoverText: "Rove",
      industry: "Airline Mile",
      link: "https://www.cosmos.so/vovavindar/rove-miles",
    },
    {
      row: 0,
      col: 1,
      type: "image",
      src: getResponsivePaths("card_render_1", "image"),
      alt: "Rove Card",
      brightness: 2,
      blur: 4,
      scale: 1.3,
      hoverText: "Rove",
      industry: "Airline Mile",
      link: "https://www.cosmos.so/vovavindar/rove-miles",
    },
    {
      row: 0,
      col: 4,
      type: "image",
      src: getResponsivePaths("paradigm_login", "image"),
      alt: "Paradigm Login",
      brightness: 1.15,
      blur: 5,
      scale: 1.2,
      hoverText: "Paradigm",
      industry: "AI",
      link: "https://www.cosmos.so/vovavindar/paradigm",
    },
    {
      row: 0,
      col: 5,
      type: "video",
      src: getResponsivePaths("align_card", "video"),
      alt: "Align Card",
      brightness: 1.2,
      blur: 3,
      scale: 1.3,
      hoverText: "Align Fund",
      className: `${styles["align-card"]}`,
      industry: "Private Equity",
      mimeType: isHEVC ? "video/mp4; codecs=hvc1" : "video/webm; codecs=vp9",
      link: "https://www.cosmos.so/vovavindar/align-fund",
    },
    /*{
      row: 0,
      col: 5,
      type: "video",
      src: "/images/optimized/paradigm/400/paradigm_launch", "video"),
      alt: "Paradigm Launch Video",
      brightness: 3,
      blur: 4,
      scale: 1.24,
      hoverText: "Paradigm",
      className: `${styles["wide"]}`,
      industry: "AI",
url: '',
    },*/
    {
      row: 1,
      col: 0,
      type: "video",
      src: getResponsivePaths("dg_animation", "video"),
      alt: "Dolce&Gabbana Website",
      brightness: 2.65,
      blur: 5,
      scale: 1.21,
      hoverText: "Dolce & Gabbana",
      industry: "NFT",
      mimeType: isHEVC ? "video/mp4; codecs=hvc1" : "video/webm; codecs=vp9",
      link: "https://www.cosmos.so/vovavindar/dolce-gabbana",
    },
    {
      row: 1,
      col: 2,
      type: "image",
      src: getResponsivePaths("am_1", "image"),
      alt: "Aya Muse Website",
      brightness: 3.2,
      blur: 6,
      scale: 1.24,
      hoverText: "Aya Muse",
      industry: "Fashion",
      link: "https://www.cosmos.so/vovavindar/aya-muse",
    },
    {
      row: 1,
      col: 7,
      type: "video",
      src: getResponsivePaths("endex_dark", "video"),
      alt: "Endex Website",
      brightness: 1.05,
      blur: 1,
      scale: 1.15,
      hoverText: "Endex",
      styles: {
        backgroundColor: "transparent",
      },
      industry: "AI",
      mimeType: isHEVC ? "video/mp4; codecs=hvc1" : "video/webm; codecs=vp9",
      link: "https://www.cosmos.so/vovavindar/endex",
    },
    {
      row: 2,
      col: 4,
      type: "image",
      src: getResponsivePaths("cognition", "image"),
      alt: "Cognition Website",
      brightness: 1.05,
      blur: 1.5,
      scale: 1.2,
      hoverText: "Cognition",
      className: `${styles["cognition"]}`,
      industry: "AI",
      link: "https://www.cosmos.so/vovavindar/cognition",
    },
    {
      row: 2,
      col: 6,
      type: "image",
      src: getResponsivePaths("mobius_1", "image"),
      alt: "3D Mobius",
      brightness: 5,
      blur: 4,
      scale: 1.38,
      hoverText: "Explorations",
      industry: "3D Art",
      link: "https://www.cosmos.so/vovavindar/explorations",
    },
    {
      row: 3,
      col: 0,
      type: "image",
      src: getResponsivePaths("blackster_logos", "image"),
      alt: "Blackster Logo",
      brightness: 5.5,
      blur: 2,
      scale: 1.5,
      hoverText: "Blackster",
      className: `${styles["blackster"]}`,
      industry: "Private Equity",
      link: "https://www.cosmos.so/vovavindar/blackster-capital",
    },
    {
      row: 3,
      col: 2,
      type: "image",
      src: getResponsivePaths("paradigm_product_1", "image"),
      alt: "Paradigm Product",
      brightness: 1.1,
      blur: 5,
      scale: 1.16,
      hoverText: "Paradigm",
      industry: "AI",
      link: "https://www.cosmos.so/vovavindar/paradigm",
    },
    /*{
      row: 3,
      col: 7,
      type: "video",
      src: "/images/optimized/1260/align_2", "video"),
      alt: "Align Website",
      brightness: 1.3,
      blur: 0,
      scale: 1.65,
      hoverText: "Align Fund",
      className: `${styles["align"]}`,
      industry: "Private Equity",
url: '',
    },*/
    {
      row: 3,
      col: 7,
      type: "video",
      src: getResponsivePaths("paradigm_cube", "video"),
      alt: "Paradigm Cube Video",
      brightness: 4,
      blur: 8,
      scale: 1.24,
      hoverText: "Paradigm",
      className: `${styles["paradigm-cube"]}`,
      industry: "AI",
      mimeType: isHEVC ? "video/mp4; codecs=hvc1" : "video/webm; codecs=vp9",
      link: "https://www.cosmos.so/vovavindar/paradigm",
    },
    {
      row: 4,
      col: 5,
      type: "video",
      src: getResponsivePaths("crystal", "video"),
      alt: "Crystal 3D Art",
      brightness: 2.5,
      blur: 6,
      scale: 1.2,
      hoverText: "Explorations",
      industry: "3D Art",
      mimeType: isHEVC ? "video/mp4; codecs=hvc1" : "video/webm; codecs=vp9",
      link: "https://www.cosmos.so/vovavindar/explorations",
    },
  ],
};

export const GRID_LAYOUT_MOBILE = {
  rows: [0, 1, 2, 3, 4],
  cols: [0, 1, 2, 3],
  media: [
    {
      row: 0,
      col: 0,
      type: "image",
      src: getResponsivePaths("app_mockup", "image"),
      alt: "Rove App",
      brightness: 2.4,
      blur: 6,
      scale: 1.14,
      hoverText: "Rove",
      industry: "Airline Mile",
      link: "https://www.cosmos.so/vovavindar/rove-miles",
    },
    {
      row: 0,
      col: 1,
      type: "image",
      src: getResponsivePaths("card_render_1", "image"),
      alt: "Rove Card",
      brightness: 2,
      blur: 4,
      scale: 1.3,
      hoverText: "Rove",
      industry: "Airline Mile",
      link: "https://www.cosmos.so/vovavindar/rove-miles",
    },
    {
      row: 1,
      col: 0,
      type: "video",
      src: getResponsivePaths("dg_animation", "video"),
      alt: "Dolce&Gabbana Website",
      brightness: 2.65,
      blur: 5,
      scale: 1.21,
      hoverText: "Dolce & Gabbana",
      industry: "NFT",
      mimeType: isHEVC ? "video/mp4; codecs=hvc1" : "video/webm; codecs=vp9",
      link: "https://www.cosmos.so/vovavindar/dolce-gabbana",
    },
    {
      row: 1,
      col: 3,
      type: "image",
      src: getResponsivePaths("am_1", "image"),
      alt: "Aya Muse Website",
      brightness: 3.2,
      blur: 6,
      scale: 1.24,
      hoverText: "Aya Muse",
      industry: "Fashion",
      link: "https://www.cosmos.so/vovavindar/aya-muse",
    },
    {
      row: 2,
      col: 2,
      type: "video",
      src: getResponsivePaths("endex_dark", "video"),
      alt: "Endex Website",
      brightness: 1.05,
      blur: 1,
      scale: 1.15,
      hoverText: "Endex",
      styles: {
        backgroundColor: "transparent",
      },
      industry: "AI",
      mimeType: isHEVC ? "video/mp4; codecs=hvc1" : "video/webm; codecs=vp9",
      link: "https://www.cosmos.so/vovavindar/endex",
    },
    {
      row: 3,
      col: 0,
      type: "image",
      src: getResponsivePaths("paradigm_product_1", "image"),
      alt: "Paradigm Product",
      brightness: 1.1,
      blur: 5,
      scale: 1.16,
      hoverText: "Paradigm",
      industry: "AI",
      link: "https://www.cosmos.so/vovavindar/paradigm",
    },
    {
      row: 4,
      col: 2,
      type: "video",
      src: getResponsivePaths("crystal", "video"),
      alt: "Crystal 3D Art",
      brightness: 2.5,
      blur: 6,
      scale: 1.2,
      hoverText: "Explorations",
      industry: "3D Art",
      mimeType: isHEVC ? "video/mp4; codecs=hvc1" : "video/webm; codecs=vp9",
      link: "https://www.cosmos.so/vovavindar/explorations",
    },
  ],
};
