// Auto-generated media paths
// Generated on: 1/23/2025, 3:19:39 PM

export const SITE_IMAGES = [
  "/images/optimized/1260/am_1.avif",
  "/images/optimized/1260/blackster_re.avif",
  "/images/optimized/1260/card_render_1.avif",
  "/images/optimized/1260/cognition_grey.avif",
  "/images/optimized/1260/jonpaulsballs.avif",
  "/images/optimized/1880/am_1.avif",
  "/images/optimized/1880/blackster_re.avif",
  "/images/optimized/1880/card_render_1.avif",
  "/images/optimized/1880/cognition_grey.avif",
  "/images/optimized/1880/jonpaulsballs.avif",
  "/images/optimized/300/am_1.avif",
  "/images/optimized/300/app_mockup.avif",
  "/images/optimized/300/blackster_logos.avif",
  "/images/optimized/300/card_render_1.avif",
  "/images/optimized/300/cognition.avif",
  "/images/optimized/300/mobius_1.avif",
  "/images/optimized/300/paradigm_login.avif",
  "/images/optimized/300/paradigm_product_1.avif",
  "/images/optimized/400/am_1.avif",
  "/images/optimized/400/app_mockup.avif",
  "/images/optimized/400/blackster_logos.avif",
  "/images/optimized/400/card_render_1.avif",
  "/images/optimized/400/cognition.avif",
  "/images/optimized/400/mobius_1.avif",
  "/images/optimized/400/paradigm_login.avif",
  "/images/optimized/400/paradigm_product_1.avif",
  "/images/optimized/650/am_1.avif",
  "/images/optimized/650/app_mockup.avif",
  "/images/optimized/650/blackster_logos.avif",
  "/images/optimized/650/card_render_1.avif",
  "/images/optimized/650/cognition.avif",
  "/images/optimized/650/mobius_1.avif",
  "/images/optimized/650/paradigm_login.avif",
  "/images/optimized/650/paradigm_product_1.avif"
];

export const SITE_VIDEOS = [
  "/images/optimized/1260/align_2.webm",
  "/images/optimized/1260/dg_animation.webm",
  "/images/optimized/1260/endex_light.webm",
  "/images/optimized/1260/paradigm_cube.webm",
  "/images/optimized/1260/twitch_clips.webm",
  "/images/optimized/1880/align_2.webm",
  "/images/optimized/1880/dg_animation.webm",
  "/images/optimized/1880/endex_light.webm",
  "/images/optimized/1880/paradigm_cube.webm",
  "/images/optimized/1880/twitch_clips.webm",
  "/images/optimized/300/align_card.webm",
  "/images/optimized/300/crystal.webm",
  "/images/optimized/300/dg_animation.webm",
  "/images/optimized/300/endex_dark.webm",
  "/images/optimized/300/paradigm_cube.webm",
  "/images/optimized/400/align_card.webm",
  "/images/optimized/400/crystal.webm",
  "/images/optimized/400/dg_animation.webm",
  "/images/optimized/400/endex_dark.webm",
  "/images/optimized/400/paradigm_cube.webm",
  "/images/optimized/650/align_card.webm",
  "/images/optimized/650/crystal.webm",
  "/images/optimized/650/dg_animation.webm",
  "/images/optimized/650/endex_dark.webm",
  "/images/optimized/650/paradigm_cube.webm"
];
